name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scan
    - cron: '0 2 * * 1'

jobs:
  secrets-scan:
    name: Secrets Detection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Scan full history
          
      # Basic secrets scan (works without API key)
      - name: Basic Secrets Scan
        run: |
          echo "🔍 Running secrets scan..."
          
          # Improved patterns that won't trigger on legitimate code
          echo "Scanning for actual API key patterns..."
          
          # Look for real API keys (not React component keys)
          if grep -r -E "(api[_-]?key|secret|token|password)\s*[:=]\s*['\"][A-Za-z0-9]{20,}['\"]" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . || true; then
            potential_secrets=$(grep -r -E "(api[_-]?key|secret|token|password)\s*[:=]\s*['\"][A-Za-z0-9]{20,}['\"]" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . || true)
            if [ ! -z "$potential_secrets" ]; then
              echo "❌ Potential hardcoded secrets found:"
              echo "$potential_secrets"
              exit 1
            fi
          fi
          
          # Look for Google API keys specifically
          if grep -r -E "AIza[0-9A-Za-z\\-_]{35}" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . || true; then
            google_keys=$(grep -r -E "AIza[0-9A-Za-z\\-_]{35}" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . || true)
            if [ ! -z "$google_keys" ]; then
              echo "❌ Google API key found in code:"
              echo "$google_keys"
              exit 1
            fi
          fi
          
          # Look for OpenAI keys
          if grep -r -E "sk-[a-zA-Z0-9]{32,}" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . || true; then
            openai_keys=$(grep -r -E "sk-[a-zA-Z0-9]{32,}" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . || true)
            if [ ! -z "$openai_keys" ]; then
              echo "❌ OpenAI API key found in code:"
              echo "$openai_keys"
              exit 1
            fi
          fi
          
          echo "✅ No hardcoded secrets detected"

  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        
      - name: Check for known vulnerabilities
        run: npx audit-ci --moderate

  environment-check:
    name: Environment Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Check for sensitive files
        run: |
          # Check that no .env files are committed
          if find . -name ".env*" -not -name ".env.example" -not -path "./.git/*" | grep -q .; then
            echo "❌ ERROR: .env files found in repository!"
            find . -name ".env*" -not -name ".env.example" -not -path "./.git/*"
            exit 1
          else
            echo "✅ No .env files found in repository"
          fi
          
      - name: Check .gitignore coverage
        run: |
          # Verify important patterns are in .gitignore
          required_patterns=(".env*" "*.key" "*.pem" ".secret" ".credentials")
          
          for pattern in "${required_patterns[@]}"; do
            if ! grep -q "$pattern" .gitignore; then
              echo "❌ WARNING: Pattern '$pattern' not found in .gitignore"
              exit 1
            else
              echo "✅ Pattern '$pattern' found in .gitignore"
            fi
          done
          
      - name: Check for hardcoded secrets patterns
        run: |
          # Basic regex patterns for common secrets (excluding false positives)
          echo "🔍 Scanning for potential hardcoded secrets..."
          
          # Check for API key patterns (exclude React component keys)
          if grep -r -E "(api[_-]?key|password|secret|token)\s*[:=]\s*['\"][A-Za-z0-9]{15,}['\"]" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . | grep -v "key.*TravelMode" | grep -v "key.*icon"; then
            echo "❌ Potential hardcoded secrets found!"
            echo "Found matches:"
            grep -r -E "(api[_-]?key|password|secret|token)\s*[:=]\s*['\"][A-Za-z0-9]{15,}['\"]" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --exclude-dir=node_modules . | grep -v "key.*TravelMode" | grep -v "key.*icon" || true
            exit 1
          fi
          
          echo "✅ No obvious hardcoded secrets detected"